[2024-03-14 16:41:34,479] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: simple.testairflow manual__2024-03-14T16:41:32.216845+00:00 [queued]>
[2024-03-14 16:41:34,502] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: simple.testairflow manual__2024-03-14T16:41:32.216845+00:00 [queued]>
[2024-03-14 16:41:34,503] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-14 16:41:34,503] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-14 16:41:34,503] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-14 16:41:34,519] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): testairflow> on 2024-03-14 16:41:32.216845+00:00
[2024-03-14 16:41:34,539] {standard_task_runner.py:52} INFO - Started process 9766 to run task
[2024-03-14 16:41:34,547] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'simple', 'testairflow', 'manual__2024-03-14T16:41:32.216845+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/etl_covid_daily.py', '--cfg-path', '/tmp/tmpoquiw6rs', '--error-file', '/tmp/tmplqc_ibxa']
[2024-03-14 16:41:34,556] {standard_task_runner.py:80} INFO - Job 50: Subtask testairflow
[2024-03-14 16:41:34,686] {task_command.py:369} INFO - Running <TaskInstance: simple.testairflow manual__2024-03-14T16:41:32.216845+00:00 [running]> on host 3751c7bf410e
[2024-03-14 16:41:34,786] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=simple
AIRFLOW_CTX_TASK_ID=testairflow
AIRFLOW_CTX_EXECUTION_DATE=2024-03-14T16:41:32.216845+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-14T16:41:32.216845+00:00
[2024-03-14 16:41:34,787] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-14 16:41:34,789] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/usr/local/bin/python3 /Users/tasyahira/Documents/bootcamp-ds/final-project/etl_src_to_stg.py']
[2024-03-14 16:41:34,804] {subprocess.py:85} INFO - Output:
[2024-03-14 16:41:34,964] {subprocess.py:92} INFO - /usr/local/bin/python3: can't open file '/Users/tasyahira/Documents/bootcamp-ds/final-project/etl_src_to_stg.py': [Errno 2] No such file or directory
[2024-03-14 16:41:34,967] {subprocess.py:96} INFO - Command exited with return code 2
[2024-03-14 16:41:34,985] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-03-14 16:41:34,990] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=simple, task_id=testairflow, execution_date=20240314T164132, start_date=20240314T164134, end_date=20240314T164134
[2024-03-14 16:41:35,001] {standard_task_runner.py:97} ERROR - Failed to execute job 50 for task testairflow (Bash command failed. The command returned a non-zero exit code 2.; 9766)
[2024-03-14 16:41:35,023] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-14 16:41:35,073] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
